version: "2"

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    volumes:
      - /usr/src/app/forcewing/static
    command: 
      gunicorn -w 2 -b :8000 run:app
      # tail -f /dev/null
    depends_on:
      - postgres

  nginx:
    restart: always
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    volumes_from:
      - web
    depends_on:
      - web

  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    build: ./postgresql
    volumes_from:
      - data
    ports:
      - "5432:5432"
