"""empty message

Revision ID: b20419874299
Revises: 79e891d817d1
Create Date: 2018-10-26 21:59:28.811079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20419874299'
down_revision = '79e891d817d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name_lower_case', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'name_lower_case')
    # ### end Alembic commands ###
