"""empty message

Revision ID: e06ef9619e9a
Revises: b20419874299
Create Date: 2018-10-26 22:12:19.560067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06ef9619e9a'
down_revision = 'b20419874299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('tag_lower_case', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'tag_lower_case')
    # ### end Alembic commands ###
